name = "psg"
version = "0.1.0"
license = "Apache-2.0"
description = "An unofficial Gleam port of PlanetScale's DatabaseJS driver"

repository = { type = "github", user = "kathrindc", repo = "galaxyscale" }
links = []

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
